---
title: "StockRecruitSET basics"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{SRbasics}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
params:
  EVAL: !r identical(Sys.getenv("NOT_CRAN"), "true")
---

```{r load_lib,message=FALSE}
library(StockRecruitSET)
library(TMB)
knitr::opts_chunk$set(warning = FALSE)
```

## Continuous Hockey-Stick Example

### Simulate data
```{r chsdat}
S = simS(n=100, pars=c(60,200))
g=1 #assume this for 
R = simR(S=S, shape="contHockey", pars=c(.5, 100, g), varlog=.1)
plot(S,R)
```

### Fit a model to the data
```{r chsfit, message=FALSE}
mod=fitSRCurve(S, R, shape="contHockey", g=g)
sdr=sdreport(mod)
summary(sdr)
```

### Estimate Blim
```{r chblim}
calcBlim(S, R)
```

### Plot the fit
```{r chsplot}
Srange=seq(min(S), max(S), length=100)
Rfit=simR(S=Srange,
		shape="contHockey", 
		pars=c(exp(mod$env$last.par[c('log_beta','log_delta')]), g)
)
plot(S, R)
lines(Srange, Rfit, col=2, lwd=3)
abline(v = calcBlim(S, R), lty=2)
```

## Ricker Example

### Simulate data
```{r rdat}
S = simS(n=100, pars=c(1,200))
R = simR(S=S, shape="Ricker", pars=c(exp(1), 1/100), varlog=0.1)
plot(S,R)
```

### Fit a model to the data
```{r rfit, message=FALSE}
mod=fitSRCurve(S, R, shape="Ricker")
sdr=sdreport(mod)
summary(sdr)
```

### Plot the fit
```{r rplot}
Srange=seq(min(S), max(S), length=100)
Rfit=simR(S=Srange,
		shape="Ricker", 
		pars=c(exp(mod$env$last.par[c('log_a','log_b')]))
)
plot(S, R)
lines(Srange, Rfit, col=2, lwd=3)
```


## Beverton-Holt Example

### Simulate data
```{r bhdat}
S = simS(n=100, pars=c(1,200))
R = simR(S=S, shape="BevertonHolt", pars=c(1.5456836,  0.0108868), varlog=0.1)
plot(S,R)
```

### Fit a model to the data
```{r bhfit, message=FALSE}
mod=fitSRCurve(S, R, shape="BevertonHolt")
sdr=sdreport(mod)
summary(sdr)
```

### Plot the fit
```{r bhplot}
Srange=seq(min(S), max(S), length=100)
Rfit=simR(S=Srange,
		shape="BevertonHolt", 
		pars=c(exp(mod$env$last.par[c('log_a','log_b')]))
)
plot(S, R)
lines(Srange, Rfit, col=2, lwd=3)
```
